import { SVGAttributes } from "react";

export default function AppLogoIcon() {
    return (
        <svg
            xmlns="http://www.w3.org/2000/svg"
            width="320"
            zoomAndPan="magnify"
            viewBox="0 0 240 239.999995"
            height="320"
            preserveAspectRatio="xMidYMid meet"
            version="1.2"
        >
            <defs>
                <clipPath id="cd137992a9">
                    <path d="M 40 38 L 200 38 L 200 199 L 40 199 Z M 40 38 " />
                </clipPath>
                <clipPath id="7bd3e60072">
                    <path d="M 39.65625 38.085938 L 200.261719 38.003906 L 200.34375 198.609375 L 39.738281 198.691406 Z M 39.65625 38.085938 " />
                </clipPath>
                <clipPath id="12b1e51231">
                    <path d="M 129.476562 44.433594 L 140.464844 67.941406 C 146.617188 81.109375 157.210938 91.691406 170.382812 97.832031 L 193.90625 108.792969 C 197.601562 110.519531 199.96875 114.226562 199.96875 118.308594 C 199.972656 122.386719 197.613281 126.097656 193.914062 127.824219 L 170.40625 138.8125 C 157.238281 144.964844 146.65625 155.558594 140.515625 168.730469 L 129.554688 192.253906 C 127.828125 195.949219 124.121094 198.316406 120.039062 198.316406 C 115.960938 198.320312 112.25 195.960938 110.523438 192.261719 L 99.535156 168.753906 C 93.382812 155.585938 82.789062 145.003906 69.617188 138.863281 L 46.09375 127.902344 C 42.398438 126.175781 40.03125 122.46875 40.03125 118.386719 C 40.027344 114.308594 42.386719 110.597656 46.085938 108.871094 L 69.59375 97.882812 C 82.761719 91.730469 93.34375 81.136719 99.484375 67.964844 L 110.445312 44.441406 C 112.171875 40.742188 115.878906 38.378906 119.960938 38.378906 C 124.039062 38.375 127.75 40.734375 129.476562 44.433594 Z M 129.476562 44.433594 " />
                </clipPath>
                <clipPath id="ccb05f3a84">
                    <path d="M 25.652344 24.097656 L 214.25 24 L 214.347656 212.597656 L 25.75 212.695312 Z M 25.652344 24.097656 " />
                </clipPath>
                <clipPath id="5e09c337e3">
                    <path d="M 39.988281 38.417969 L 199.929688 38.335938 L 200.011719 198.277344 L 40.070312 198.359375 Z M 39.988281 38.417969 " />
                </clipPath>
                <linearGradient
                    x1="19.391703"
                    gradientTransform="matrix(0.736715,-0.000375739,0.000375739,0.736715,25.652453,24.096189)"
                    y1="128"
                    x2="236.608274"
                    gradientUnits="userSpaceOnUse"
                    y2="128"
                    id="da8eec584a"
                >
                    <stop
                        className="stop-color:#fff7ad;stop-opacity:1;"
                        offset="0"
                    />
                    <stop
                        className="stop-color:#fff7ad;stop-opacity:1;"
                        offset="0.0078125"
                    />
                    <stop
                        className="stop-color:#fff6ae;stop-opacity:1;"
                        offset="0.015625"
                    />
                    <stop
                        className="stop-color:#fff6ae;stop-opacity:1;"
                        offset="0.0234375"
                    />
                    <stop
                        className="stop-color:#fff5af;stop-opacity:1;"
                        offset="0.03125"
                    />
                    <stop
                        className="stop-color:#fff4b0;stop-opacity:1;"
                        offset="0.0390625"
                    />
                    <stop
                        className="stop-color:#fff4b0;stop-opacity:1;"
                        offset="0.046875"
                    />
                    <stop
                        className="stop-color:#fff3b1;stop-opacity:1;"
                        offset="0.0546875"
                    />
                    <stop
                        className="stop-color:#fff3b1;stop-opacity:1;"
                        offset="0.0625"
                    />
                    <stop
                        className="stop-color:#fff2b2;stop-opacity:1;"
                        offset="0.0703125"
                    />
                    <stop
                        className="stop-color:#fff1b3;stop-opacity:1;"
                        offset="0.078125"
                    />
                    <stop
                        className="stop-color:#fff1b3;stop-opacity:1;"
                        offset="0.0859375"
                    />
                    <stop
                        className="stop-color:#fff0b4;stop-opacity:1;"
                        offset="0.09375"
                    />
                    <stop
                        className="stop-color:#ffefb4;stop-opacity:1;"
                        offset="0.101562"
                    />
                    <stop
                        className="stop-color:#ffefb5;stop-opacity:1;"
                        offset="0.109375"
                    />
                    <stop
                        className="stop-color:#ffeeb5;stop-opacity:1;"
                        offset="0.117187"
                    />
                    <stop
                        className="stop-color:#ffeeb6;stop-opacity:1;"
                        offset="0.125"
                    />
                    <stop
                        className="stop-color:#ffedb7;stop-opacity:1;"
                        offset="0.132813"
                    />
                    <stop
                        className="stop-color:#ffecb7;stop-opacity:1;"
                        offset="0.140625"
                    />
                    <stop
                        className="stop-color:#ffecb8;stop-opacity:1;"
                        offset="0.148438"
                    />
                    <stop
                        className="stop-color:#ffebb8;stop-opacity:1;"
                        offset="0.15625"
                    />
                    <stop
                        className="stop-color:#ffebb9;stop-opacity:1;"
                        offset="0.164063"
                    />
                    <stop
                        className="stop-color:#ffeaba;stop-opacity:1;"
                        offset="0.171875"
                    />
                    <stop
                        className="stop-color:#ffe9ba;stop-opacity:1;"
                        offset="0.179688"
                    />
                    <stop
                        className="stop-color:#ffe9bb;stop-opacity:1;"
                        offset="0.1875"
                    />
                    <stop
                        className="stop-color:#ffe8bb;stop-opacity:1;"
                        offset="0.195312"
                    />
                    <stop
                        className="stop-color:#ffe8bc;stop-opacity:1;"
                        offset="0.203125"
                    />
                    <stop
                        className="stop-color:#ffe7bd;stop-opacity:1;"
                        offset="0.210938"
                    />
                    <stop
                        className="stop-color:#ffe6bd;stop-opacity:1;"
                        offset="0.21875"
                    />
                    <stop
                        className="stop-color:#ffe6be;stop-opacity:1;"
                        offset="0.226562"
                    />
                    <stop
                        className="stop-color:#ffe5be;stop-opacity:1;"
                        offset="0.234375"
                    />
                    <stop
                        className="stop-color:#ffe5bf;stop-opacity:1;"
                        offset="0.242188"
                    />
                    <stop
                        className="stop-color:#ffe4c0;stop-opacity:1;"
                        offset="0.25"
                    />
                    <stop
                        className="stop-color:#ffe3c0;stop-opacity:1;"
                        offset="0.257812"
                    />
                    <stop
                        className="stop-color:#ffe3c1;stop-opacity:1;"
                        offset="0.265625"
                    />
                    <stop
                        className="stop-color:#ffe2c1;stop-opacity:1;"
                        offset="0.273438"
                    />
                    <stop
                        className="stop-color:#ffe1c2;stop-opacity:1;"
                        offset="0.28125"
                    />
                    <stop
                        className="stop-color:#ffe1c3;stop-opacity:1;"
                        offset="0.289063"
                    />
                    <stop
                        className="stop-color:#ffe0c3;stop-opacity:1;"
                        offset="0.296875"
                    />
                    <stop
                        className="stop-color:#ffe0c4;stop-opacity:1;"
                        offset="0.304688"
                    />
                    <stop
                        className="stop-color:#ffdfc4;stop-opacity:1;"
                        offset="0.3125"
                    />
                    <stop
                        className="stop-color:#ffdec5;stop-opacity:1;"
                        offset="0.320313"
                    />
                    <stop
                        className="stop-color:#ffdec6;stop-opacity:1;"
                        offset="0.328125"
                    />
                    <stop
                        className="stop-color:#ffddc6;stop-opacity:1;"
                        offset="0.335938"
                    />
                    <stop
                        className="stop-color:#ffddc7;stop-opacity:1;"
                        offset="0.34375"
                    />
                    <stop
                        className="stop-color:#ffdcc7;stop-opacity:1;"
                        offset="0.351563"
                    />
                    <stop
                        className="stop-color:#ffdbc8;stop-opacity:1;"
                        offset="0.359375"
                    />
                    <stop
                        className="stop-color:#ffdbc8;stop-opacity:1;"
                        offset="0.367188"
                    />
                    <stop
                        className="stop-color:#ffdac9;stop-opacity:1;"
                        offset="0.375"
                    />
                    <stop
                        className="stop-color:#ffdaca;stop-opacity:1;"
                        offset="0.382813"
                    />
                    <stop
                        className="stop-color:#ffd9ca;stop-opacity:1;"
                        offset="0.390625"
                    />
                    <stop
                        className="stop-color:#ffd8cb;stop-opacity:1;"
                        offset="0.398438"
                    />
                    <stop
                        className="stop-color:#ffd8cb;stop-opacity:1;"
                        offset="0.40625"
                    />
                    <stop
                        className="stop-color:#ffd7cc;stop-opacity:1;"
                        offset="0.414063"
                    />
                    <stop
                        className="stop-color:#ffd6cd;stop-opacity:1;"
                        offset="0.421875"
                    />
                    <stop
                        className="stop-color:#ffd6cd;stop-opacity:1;"
                        offset="0.429688"
                    />
                    <stop
                        className="stop-color:#ffd5ce;stop-opacity:1;"
                        offset="0.4375"
                    />
                    <stop
                        className="stop-color:#ffd5ce;stop-opacity:1;"
                        offset="0.445313"
                    />
                    <stop
                        className="stop-color:#ffd4cf;stop-opacity:1;"
                        offset="0.453125"
                    />
                    <stop
                        className="stop-color:#ffd3d0;stop-opacity:1;"
                        offset="0.460938"
                    />
                    <stop
                        className="stop-color:#ffd3d0;stop-opacity:1;"
                        offset="0.46875"
                    />
                    <stop
                        className="stop-color:#ffd2d1;stop-opacity:1;"
                        offset="0.476563"
                    />
                    <stop
                        className="stop-color:#ffd2d1;stop-opacity:1;"
                        offset="0.484375"
                    />
                    <stop
                        className="stop-color:#ffd1d2;stop-opacity:1;"
                        offset="0.492188"
                    />
                    <stop
                        className="stop-color:#ffd0d3;stop-opacity:1;"
                        offset="0.5"
                    />
                    <stop
                        className="stop-color:#ffd0d3;stop-opacity:1;"
                        offset="0.507812"
                    />
                    <stop
                        className="stop-color:#ffcfd4;stop-opacity:1;"
                        offset="0.515625"
                    />
                    <stop
                        className="stop-color:#ffcfd4;stop-opacity:1;"
                        offset="0.523438"
                    />
                    <stop
                        className="stop-color:#ffced5;stop-opacity:1;"
                        offset="0.53125"
                    />
                    <stop
                        className="stop-color:#ffcdd6;stop-opacity:1;"
                        offset="0.539063"
                    />
                    <stop
                        className="stop-color:#ffcdd6;stop-opacity:1;"
                        offset="0.546875"
                    />
                    <stop
                        className="stop-color:#ffccd7;stop-opacity:1;"
                        offset="0.554688"
                    />
                    <stop
                        className="stop-color:#ffccd7;stop-opacity:1;"
                        offset="0.5625"
                    />
                    <stop
                        className="stop-color:#ffcbd8;stop-opacity:1;"
                        offset="0.570313"
                    />
                    <stop
                        className="stop-color:#ffcad9;stop-opacity:1;"
                        offset="0.578125"
                    />
                    <stop
                        className="stop-color:#ffcad9;stop-opacity:1;"
                        offset="0.585938"
                    />
                    <stop
                        className="stop-color:#ffc9da;stop-opacity:1;"
                        offset="0.59375"
                    />
                    <stop
                        className="stop-color:#ffc8da;stop-opacity:1;"
                        offset="0.601563"
                    />
                    <stop
                        className="stop-color:#ffc8db;stop-opacity:1;"
                        offset="0.609375"
                    />
                    <stop
                        className="stop-color:#ffc7db;stop-opacity:1;"
                        offset="0.617188"
                    />
                    <stop
                        className="stop-color:#ffc7dc;stop-opacity:1;"
                        offset="0.625"
                    />
                    <stop
                        className="stop-color:#ffc6dd;stop-opacity:1;"
                        offset="0.632813"
                    />
                    <stop
                        className="stop-color:#ffc5dd;stop-opacity:1;"
                        offset="0.640625"
                    />
                    <stop
                        className="stop-color:#ffc5de;stop-opacity:1;"
                        offset="0.648438"
                    />
                    <stop
                        className="stop-color:#ffc4de;stop-opacity:1;"
                        offset="0.65625"
                    />
                    <stop
                        className="stop-color:#ffc4df;stop-opacity:1;"
                        offset="0.664063"
                    />
                    <stop
                        className="stop-color:#ffc3e0;stop-opacity:1;"
                        offset="0.671875"
                    />
                    <stop
                        className="stop-color:#ffc2e0;stop-opacity:1;"
                        offset="0.679688"
                    />
                    <stop
                        className="stop-color:#ffc2e1;stop-opacity:1;"
                        offset="0.6875"
                    />
                    <stop
                        className="stop-color:#ffc1e1;stop-opacity:1;"
                        offset="0.695313"
                    />
                    <stop
                        className="stop-color:#ffc1e2;stop-opacity:1;"
                        offset="0.703125"
                    />
                    <stop
                        className="stop-color:#ffc0e3;stop-opacity:1;"
                        offset="0.710938"
                    />
                    <stop
                        className="stop-color:#ffbfe3;stop-opacity:1;"
                        offset="0.71875"
                    />
                    <stop
                        className="stop-color:#ffbfe4;stop-opacity:1;"
                        offset="0.726563"
                    />
                    <stop
                        className="stop-color:#ffbee4;stop-opacity:1;"
                        offset="0.734375"
                    />
                    <stop
                        className="stop-color:#ffbde5;stop-opacity:1;"
                        offset="0.742188"
                    />
                    <stop
                        className="stop-color:#ffbde6;stop-opacity:1;"
                        offset="0.75"
                    />
                    <stop
                        className="stop-color:#ffbce6;stop-opacity:1;"
                        offset="0.757813"
                    />
                    <stop
                        className="stop-color:#ffbce7;stop-opacity:1;"
                        offset="0.765625"
                    />
                    <stop
                        className="stop-color:#ffbbe7;stop-opacity:1;"
                        offset="0.773438"
                    />
                    <stop
                        className="stop-color:#ffbae8;stop-opacity:1;"
                        offset="0.78125"
                    />
                    <stop
                        className="stop-color:#ffbae9;stop-opacity:1;"
                        offset="0.789063"
                    />
                    <stop
                        className="stop-color:#ffb9e9;stop-opacity:1;"
                        offset="0.796875"
                    />
                    <stop
                        className="stop-color:#ffb9ea;stop-opacity:1;"
                        offset="0.804688"
                    />
                    <stop
                        className="stop-color:#ffb8ea;stop-opacity:1;"
                        offset="0.8125"
                    />
                    <stop
                        className="stop-color:#ffb7eb;stop-opacity:1;"
                        offset="0.820313"
                    />
                    <stop
                        className="stop-color:#ffb7ec;stop-opacity:1;"
                        offset="0.828125"
                    />
                    <stop
                        className="stop-color:#ffb6ec;stop-opacity:1;"
                        offset="0.835938"
                    />
                    <stop
                        className="stop-color:#ffb6ed;stop-opacity:1;"
                        offset="0.84375"
                    />
                    <stop
                        className="stop-color:#ffb5ed;stop-opacity:1;"
                        offset="0.851563"
                    />
                    <stop
                        className="stop-color:#ffb4ee;stop-opacity:1;"
                        offset="0.859375"
                    />
                    <stop
                        className="stop-color:#ffb4ef;stop-opacity:1;"
                        offset="0.867188"
                    />
                    <stop
                        className="stop-color:#ffb3ef;stop-opacity:1;"
                        offset="0.875"
                    />
                    <stop
                        className="stop-color:#ffb2f0;stop-opacity:1;"
                        offset="0.882813"
                    />
                    <stop
                        className="stop-color:#ffb2f0;stop-opacity:1;"
                        offset="0.890625"
                    />
                    <stop
                        className="stop-color:#ffb1f1;stop-opacity:1;"
                        offset="0.898438"
                    />
                    <stop
                        className="stop-color:#ffb1f1;stop-opacity:1;"
                        offset="0.90625"
                    />
                    <stop
                        className="stop-color:#ffb0f2;stop-opacity:1;"
                        offset="0.914063"
                    />
                    <stop
                        className="stop-color:#ffaff3;stop-opacity:1;"
                        offset="0.921875"
                    />
                    <stop
                        className="stop-color:#ffaff3;stop-opacity:1;"
                        offset="0.929688"
                    />
                    <stop
                        className="stop-color:#ffaef4;stop-opacity:1;"
                        offset="0.9375"
                    />
                    <stop
                        className="stop-color:#ffaef4;stop-opacity:1;"
                        offset="0.945313"
                    />
                    <stop
                        className="stop-color:#ffadf5;stop-opacity:1;"
                        offset="0.953125"
                    />
                    <stop
                        className="stop-color:#ffacf6;stop-opacity:1;"
                        offset="0.960938"
                    />
                    <stop
                        className="stop-color:#ffacf6;stop-opacity:1;"
                        offset="0.96875"
                    />
                    <stop
                        className="stop-color:#ffabf7;stop-opacity:1;"
                        offset="0.976563"
                    />
                    <stop
                        className="stop-color:#ffabf7;stop-opacity:1;"
                        offset="0.984375"
                    />
                    <stop
                        className="stop-color:#ffaaf8;stop-opacity:1;"
                        offset="0.992188"
                    />
                    <stop
                        className="stop-color:#ffa9f9;stop-opacity:1;"
                        offset="1"
                    />
                </linearGradient>
            </defs>
            <g id="3d03946357">
                <g clipRule="nonzero" clipPath="url(#cd137992a9)">
                    <g clipRule="nonzero" clipPath="url(#7bd3e60072)">
                        <g clipRule="nonzero" clipPath="url(#12b1e51231)">
                            <g clipRule="nonzero" clipPath="url(#ccb05f3a84)">
                                <g
                                    clipRule="nonzero"
                                    clipPath="url(#5e09c337e3)"
                                >
                                    <path
                                        className=" stroke:none;fill-rule:nonzero;fill:url(#linear0);"
                                        d="M 39.945312 38.375 L 40.027344 198.402344 L 200.054688 198.320312 L 199.972656 38.292969 Z M 39.945312 38.375 "
                                    />
                                </g>
                            </g>
                        </g>
                    </g>
                </g>
            </g>
        </svg>
    );
}
